
import java.net.Inet4Address;
import java.rmi.RemoteException;
import java.rmi.registry.LocateRegistry;
import java.rmi.registry.Registry;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JTextField;
import javax.swing.UIManager;
import rmi.RMI;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author JH
 */
public class LoginWindow extends javax.swing.JFrame {

   RMI rmi;

   /**
    * Creates new form LoginWindow
    */
   public LoginWindow() {
      try {
         initComponents();
         Registry registry = LocateRegistry.createRegistry(9001);
         registry.rebind("RTPhoneClient", new RMIClient());
         System.out.println("start");
      } catch (RemoteException ex) {
         Logger.getLogger(LoginWindow.class.getName()).log(Level.SEVERE, null, ex);
      }
   }

   public RMI getRmi() {
      return rmi;
   }

   public JTextField getjTextFieldHost() {
      return jTextFieldHost;
   }
   
   public JTextField getjTextFieldUsername() {
      return jTextFieldUsername;
   }

   public JPasswordField getjPasswordField() {
      return jPasswordField;
   }

   public void setRmi(RMI rmi) {
      this.rmi = rmi;
   }

   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      jLabel1 = new javax.swing.JLabel();
      jLabel2 = new javax.swing.JLabel();
      jLabel3 = new javax.swing.JLabel();
      jTextFieldHost = new javax.swing.JTextField();
      jTextFieldUsername = new javax.swing.JTextField();
      jPasswordField = new javax.swing.JPasswordField();
      jButtonRegister = new javax.swing.JButton();
      jButtonLogin = new javax.swing.JButton();

      setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

      jLabel1.setText("Host:");

      jLabel2.setText("Username:");

      jLabel3.setText("Password:");

      jTextFieldHost.setText("127.0.0.1");

      jTextFieldUsername.setText("user0");

      jPasswordField.setText("password0");

      jButtonRegister.setText("Register");
      jButtonRegister.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButtonRegisterActionPerformed(evt);
         }
      });

      jButtonLogin.setText("Login");
      jButtonLogin.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButtonLoginActionPerformed(evt);
         }
      });

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                  .addGroup(layout.createSequentialGroup()
                     .addComponent(jLabel1)
                     .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                     .addComponent(jTextFieldHost))
                  .addGroup(layout.createSequentialGroup()
                     .addComponent(jLabel2)
                     .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                     .addComponent(jTextFieldUsername))
                  .addGroup(layout.createSequentialGroup()
                     .addComponent(jLabel3)
                     .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                     .addComponent(jPasswordField, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)))
               .addGroup(layout.createSequentialGroup()
                  .addComponent(jButtonRegister)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                  .addComponent(jButtonLogin)))
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(jLabel1)
               .addComponent(jTextFieldHost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(jLabel2)
               .addComponent(jTextFieldUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(jLabel3)
               .addComponent(jPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(jButtonRegister)
               .addComponent(jButtonLogin))
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
      );

      pack();
   }// </editor-fold>//GEN-END:initComponents

   private void jButtonLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLoginActionPerformed
      try {
         Registry registry = LocateRegistry.getRegistry(this.jTextFieldHost.getText(), 9000);
         rmi = (RMI) registry.lookup("RTPhoneServer");
         boolean check = rmi.login(this.jTextFieldUsername.getText(), this.jPasswordField.getText(), Inet4Address.getLocalHost().getHostAddress().toString());
         if (check) {
            JOptionPane.showMessageDialog(null, "ok");
            rmi.getLoggedUsers();
            rmi.getRegisteredUsers();
            this.setVisible(false);
            new MainWindow(this).setVisible(true);
         } else {
            JOptionPane.showMessageDialog(null, "erro");
         }

      } catch (Exception e) {
         System.out.println(e);
         System.out.println(this.jTextFieldHost.getText());
      }
   }//GEN-LAST:event_jButtonLoginActionPerformed

   private void jButtonRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegisterActionPerformed
      try {
         Registry registry = LocateRegistry.getRegistry(this.jTextFieldHost.getText(), 9000);
         rmi = (RMI) registry.lookup("RTPhoneServer");
         boolean check = rmi.register(this.jTextFieldUsername.getText(), this.jPasswordField.getText());
         if (check) {
            JOptionPane.showMessageDialog(null, "ok");
         } else {
            JOptionPane.showMessageDialog(null, "erro");
         }
      } catch (Exception e) {
         System.out.println(e);
      }
   }//GEN-LAST:event_jButtonRegisterActionPerformed

   /**
    * @param args the command line arguments
    */
   public static void main(String args[]) {
      /* Set the Nimbus look and feel */
      //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
       * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
       */
      try {
         UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
      } catch (ClassNotFoundException ex) {
         java.util.logging.Logger.getLogger(LoginWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (InstantiationException ex) {
         java.util.logging.Logger.getLogger(LoginWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (IllegalAccessException ex) {
         java.util.logging.Logger.getLogger(LoginWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (javax.swing.UnsupportedLookAndFeelException ex) {
         java.util.logging.Logger.getLogger(LoginWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      }
      //</editor-fold>

      /* Create and display the form */
      java.awt.EventQueue.invokeLater(new Runnable() {
         public void run() {
            new LoginWindow().setVisible(true);
         }
      });
   }
   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JButton jButtonLogin;
   private javax.swing.JButton jButtonRegister;
   private javax.swing.JLabel jLabel1;
   private javax.swing.JLabel jLabel2;
   private javax.swing.JLabel jLabel3;
   private javax.swing.JPasswordField jPasswordField;
   private javax.swing.JTextField jTextFieldHost;
   private javax.swing.JTextField jTextFieldUsername;
   // End of variables declaration//GEN-END:variables
}
