/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import database.Client;
import database.ClientMessage;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import remoteMethodInvocation.util.SendMessageThread;

/**
 *
 * @author JH
 */
public class ChatTabPanel extends javax.swing.JPanel {

   private MainWindow mainWindow;
   private database.Client client;
   private ArrayList<ClientMessage> actualMessageList;

   /**
    * Creates new form ChatTabPanel
    */
   public ChatTabPanel(MainWindow mainWindow, database.Client client) {
      this.actualMessageList = new ArrayList<>();
      this.client = client;
      this.mainWindow = mainWindow;
      initComponents();
   }

   public Client getClient() {
      return client;
   }

   public MainWindow getMainWindow() {
      return mainWindow;
   }

   public void append(ClientMessage clientMessage) {
      if (clientMessage.getIndex() == -1) {
         jTextAreaChat.setText(jTextAreaChat.getText() + clientMessage.toString());
      } else {
         boolean ok = false;
         for (int index = 0; index < actualMessageList.size(); index++) {
            if (actualMessageList.get(index).getIndex() > clientMessage.getIndex()) {
               actualMessageList.add(index, clientMessage);
               ok = true;
            }
         }
         if(!ok){
            actualMessageList.add(clientMessage);
         }
         String temp = "";
         for (int index = 0; index < actualMessageList.size(); index++) {
            temp += actualMessageList.get(index).toString();
         }
         jTextAreaChat.setText(temp);
      }
   }

   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaSend = new javax.swing.JTextArea();
        jCheckBoxSend = new javax.swing.JCheckBox();
        jButtonSend = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaChat = new javax.swing.JTextArea();

        jTextAreaSend.setColumns(20);
        jTextAreaSend.setRows(2);
        jTextAreaSend.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextAreaSendKeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(jTextAreaSend);

        jCheckBoxSend.setText("Enter to send");

        jButtonSend.setText("Send");
        jButtonSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSendActionPerformed(evt);
            }
        });

        jTextAreaChat.setEditable(false);
        jTextAreaChat.setColumns(20);
        jTextAreaChat.setRows(5);
        jScrollPane1.setViewportView(jTextAreaChat);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonSend, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCheckBoxSend))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jCheckBoxSend)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonSend))
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

   private void sendMessage() {
      SendMessageThread sendMessageThread = new SendMessageThread(mainWindow, client, jTextAreaSend);
      sendMessageThread.start();
      this.mainWindow.getLoginWindow().getDefaultServerConfigurationsWindow().getDatabase().removeMessageList(client.getUsername(), this.mainWindow.getMe().getUsername());
      ClientMessage clientMessage = new ClientMessage(getMainWindow().getMe(), getClient(), jTextAreaSend.getText());
      jTextAreaChat.setText(jTextAreaChat.getText() + clientMessage.toString());
   }

   private void jButtonSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSendActionPerformed
      sendMessage();
   }//GEN-LAST:event_jButtonSendActionPerformed

    private void jTextAreaSendKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextAreaSendKeyReleased
       if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
          if (jCheckBoxSend.isSelected()) {
             sendMessage();
          }
       }
    }//GEN-LAST:event_jTextAreaSendKeyReleased
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonSend;
    private javax.swing.JCheckBox jCheckBoxSend;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextAreaChat;
    private javax.swing.JTextArea jTextAreaSend;
    // End of variables declaration//GEN-END:variables
}
